### ISSUE TITLE
SpaceX Dashboard Challenge

### ISSUE THREAD

**Issue by AkhilXavier95** [mrakkyX/bigbinary-interview-for-45327726#1]
https://public.3.basecamp.com/p/UGEyqrnc11MEXx8ndGmJcA49

**Comment by AkhilXavier95** [comment]
The application is ready for code review.

**Comment by vinay0x** [comment]
@mrakkyX Please add a link to the deployed app.

**Comment by AkhilXavier95** [comment]
@vinay0x  sorry, I forgot to add the deployed URL.

https://interview-space-x.herokuapp.com
